lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/workflows/linting.yml
    - assets/sendmail_template.txt
    - lib/NfcoreSchema.groovy
    - lib/NfcoreTemplate.groovy
  files_exist:
    - bin/scrape_software_versions.py
    - modules/local/get_software_versions.nf
  actions_awsfulltest: False
